//
//  DHController+Exchange.swift
//  SatispayInStore
//
//  Created by Pierluigi D'Andrea on 09/10/17.
//  Copyright © 2017 Satispay. All rights reserved.
//

import Foundation

extension DHController {

    /// Starts the Diffie-Hellman exchange sending P, G and PublicKey to the server.
    ///
    /// - Parameters:
    ///   - params: DH parameters generated by `generateParameters`.
    public func exchange(parameters params: DHParams,
                         completionHandler: @escaping CompletionHandler<(DHParams, DHExchangeResponse)>) -> CancellableOperation? {

        guard let exchangeRequest = DHExchangeRequest(params: params) else {
            completionHandler(nil, .any(DHError.invalidDHParams))
            return nil
        }

        return DHService.exchange(request: exchangeRequest).request { (response: DHExchangeResponse?, _, error: NetworkServiceError?) in

            guard let response = response else {
                return completionHandler(nil, .any(DHError.exchangeResponseFailure))
            }

            completionHandler((params, response), error)

        }

    }

}
